version: '3.7'
services:
  aidbox-db:
    image: healthsamurai/aidboxdb:15.3
    pull_policy: always
    ports:
      - "${PGHOSTPORT}:5432"
    volumes:
      - "./pgdata:/data"
    environment:
      POSTGRES_USER:     "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB:       "${PGDATABASE}"

  aidbox:
    image: healthsamurai/aidboxone:edge
    pull_policy: always
    depends_on: ["aidbox-db"]
    CCDA_CUSTOM_RULES:
      aidbox.ccda.rules.encounters/narrative:
        select:
          - selector:
              cda:  [text 0 cols 1]
              fhir: [entry * type 0]
            override:
              cda:  [text 0 cols 1]
              fhir: [entry * class]
      aidbox.ccda.rules.vital-signs/narrative:
        assoc:
          - cda: [text 0]
            const:
              type: table
              header:
                - Vital sign
                - Date
                - Value and units
          - fhir: [entry *]
            cda: [text 0 rows]
            apply-rules:
              - fhir: [code]
                cda: [0]
              - fhir: [effective]
                cda: [1]
              - fhir: [value]
                cda: [2]
    ports:
      - "${AIDBOX_PORT}:${AIDBOX_PORT}"
      - "${BOX_METRICS_PORT}:${BOX_METRICS_PORT}"
    volumes:
      - "./zrc:/aidbox-project/zrc"
      - "./zen-package.edn:/aidbox-project/zen-package.edn"
      - "./zen-packages:/aidbox-project/zen-packages"
    env_file:
      - .env
    environment:
      BOX_PROJECT_GIT_TARGET__PATH: /aidbox-project
      AIDBOX_ZEN_ENTRYPOINT: main/box
      AIDBOX_DEV_MODE: "true"
      AIDBOX_ZEN_DEV_MODE: "true"
      PGPORT: 5432
      PGHOST: aidbox-db
