version: '3.7'
volumes:
  prometheus-data:
  grafana-data:
services:
  aidbox-db:
    image: healthsamurai/aidboxdb:15.3
    pull_policy: always
    ports:
      - "${PGHOSTPORT}:5432"
    volumes:
      - "./pgdata:/data"
    environment:
      POSTGRES_USER:     "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB:       "${PGDATABASE}"

  aidbox:
    image: healthsamurai/aidboxone:edge
    pull_policy: always
    depends_on: ["aidbox-db"]
    links:
      - "aidbox-db:database"
    ports:
      - "${AIDBOX_PORT}:${AIDBOX_PORT}"
      - "${BOX_METRICS_PORT}:${BOX_METRICS_PORT}"
    volumes:
      - "./zrc:/aidbox-project/zrc"
      - "./zen-package.edn:/aidbox-project/zen-package.edn"
      - "./zen-packages:/aidbox-project/zen-packages"
    env_file:
      - .env
    environment:
      BOX_PROJECT_GIT_TARGET__PATH: /aidbox-project
      AIDBOX_ZEN_ENTRYPOINT: main/box
      AIDBOX_DEV_MODE: "true"
      AIDBOX_ZEN_DEV_MODE: "true"
      PGPORT: 5432
      PGHOST: aidbox-db

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: unless-stopped
    ports:
      - 9091:9091

  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: "prometheus"
    # env_file:
    #   - .env
    environment:
      V: 'v5'
    ports:
      - 9090:9090
    volumes:
      - ./audit/prometheus/:/etc/prometheus/:cached
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - pushgateway
    extra_hosts:
      - aidbox:host-gateway

  grafana:
    environment:
      V: 'v5'
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_SECURITY_COOKIE_SECURITY: "false"
      GF_SECURITY_COOKIE_SAMESITE: "disabled"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./audit/grafana/provisioning:/etc/grafana/provisioning:cached
    image: grafana/grafana:10.0.0
    ports:
      - 3000:3000

  subscription-demo-server:
    image: healthsamurai/aidboxone:edge
    pull_policy: always
    links:
      - "aidbox-db:database"
    ports:
      - "9001:9001"
    env_file:
      - .env
    environment:
      AIDBOX_HOST: "http://aidbox:${AIDBOX_PORT}"
      SUBSCRIBER_HOST: "http://subscription-demo-server:9000"
    entrypoint: ["java", "-XX:-OmitStackTraceInFastThrow", "-jar", "/aidbox.jar", "-m", "fhir.topic-based-subscription.demo-server"]
