{
 "title": "Aidbox",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests per minute (rpm)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "ts", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ev:\"w/resp\"",
     "timeField": "ts"
    }
   ]
  },
  {
   "title": "Request Per Day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "ts", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ev:\"w/resp\"",
     "timeField": "ts"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "size",
       "id": "1",
       "meta": {
        "max": true,
        "std_deviation_bounds_lower": false,
        "std_deviation_bounds_upper": false,
        "sum": false
       },
       "type": "extended_stats"
      }
     ],
     "query": "ev:\"db/db-size\"",
     "timeField": "ts"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "ts", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "lvl.keyword:\"error\"",
     "timeField": "ts"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "w_r.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" },
      { "field": "d", "id": "3", "type": "sum" },
      { "field": "d", "id": "4", "type": "avg" },
      { "field": "d", "id": "5", "type": "max" },
      { "field": "d", "id": "6", "type": "min" }
     ],
     "query": "ev:\"w/resp\" AND NOT w_url:\"/_health\" AND w_r.keyword:*",
     "timeField": "ts"
    }
   ]
  },
  {
   "title": "Request's Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "d", "id": "2", "settings": { "interval": "100", "min_doc_count": "0" }, "type": "histogram" },
      { "field": "ts", "id": "3", "settings": { "interval": "5m", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "ev:\"w/resp\"",
     "timeField": "ts"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "100" }, "type": "raw_data" }
     ],
     "query": "ev:\"db/q\"",
     "timeField": "ts"
    }
   ]
  },
  {
   "title": "Users/Clients Online",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "Users",
     "bucketAggs": [
      { "field": "ts", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "w_uid.keyword", "id": "1", "type": "cardinality" }
     ],
     "timeField": "ts"
    },
    {
     "alias": "Cliets",
     "bucketAggs": [
      { "field": "ts", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "w_cid.keyword", "id": "1", "type": "cardinality" }
     ],
     "timeField": "ts"
    }
   ]
  },
  {
   "title": "Mean request http/db",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "http",
     "bucketAggs": [
      { "field": "ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "d", "id": "1", "type": "avg" }
     ],
     "query": "ev:\"w/resp\"",
     "timeField": "ts"
    },
    {
     "alias": "db",
     "bucketAggs": [
      { "field": "ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "d", "id": "1", "type": "avg" }
     ],
     "query": "ev:\"db/q\" AND ctx:*",
     "timeField": "ts"
    }
   ]
  },
  {
   "title": "Top Tables",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "tbl.keyword",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "size", "id": "1", "type": "avg" },
      { "field": "est_tuples", "id": "3", "type": "avg" }
     ],
     "query": "ev:tbl-size AND tbl:* ",
     "timeField": "ts"
    }
   ]
  }
 ]
}