{
 "title": "JVM Info",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "JVM memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "jvm_heap_memory", "legendFormat": "heap" },
    { "expr": "jvm_non_heap_memory", "legendFormat": "nonheap" },
    { "expr": "jvm_total_memory_size", "legendFormat": "total" },
    { "expr": "jvm_max_memory_size", "legendFormat": "max" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "# JVM Metrics\n\n## total\n\n` jvm_total_memory_size - java.lang.Runtime/totalMemory`\n\nReturns the total amount of memory in the Java virtual machine. The value returned by this method may vary over time, depending on the host environment.\nNote that the amount of memory required to hold an object of any given type may be implementation-dependen\n\n## max\n\n`jvm_max_memory_size - java.lang.Runtime/totalMemory`\n\nReturns the maximum amount of memory that the Java virtual machine will attempt to use.\n\n"
   }
  },
  {
   "title": "JVM threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "jvm_thread_count", "legendFormat": "threads" },
    { "expr": "jvm_thread_peak_count", "legendFormat": "peak" },
    { "expr": "jvm_thread_daemon_count", "legendFormat": "daemon" },
    { "expr": "jvm_available_processors_size", "legendFormat": "cpus" }
   ]
  },
  {
   "title": "JVM gc count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "jvm_gc_count", "legendFormat": "{{gc}}" }
   ]
  },
  {
   "title": "JVM gc time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "rate(jvm_gc_time[5m])", "legendFormat": "{{gc}}" }
   ]
  }
 ]
}