{
 "title": "Aidbox Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aidbox_http_request_duration_seconds_count[1m]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aidbox_http_request_duration_seconds_sum[5m]))/sum(rate(aidbox_http_request_duration_seconds_count[5m]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(aidbox_http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "d99"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(aidbox_http_request_wait_seconds_bucket[1m])) by (le))",
     "legendFormat": "wait99"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "httpkit_active_count/httpkit_max_size",
     "legendFormat": "httpkit  pool load"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "httpkit_queue_count", "legendFormat": "httpkit queue" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aidbox_http_request_duration_seconds_count{status=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(hikari_timeout_total[5m])", "legendFormat": "hikari timeout" }
   ]
  },
  {
   "title": "pg read/write",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_requests_total[1h])/(rate(pg_updates_total[1h]) + rate(pg_inserts_total[1h]) + rate(pg_deletes_total[1h])) ",
     "legendFormat": "read/write"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size{datname=\"protodev\", job=\"aidbox-hours\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(aidbox_http_request_duration_seconds_count[1h]))"
    }
   ]
  },
  {
   "title": "requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(aidbox_http_request_duration_seconds_count[5m]))",
     "legendFormat": "box req"
    },
    {
     "expr": "sum(rate(aidbox_http_request_duration_seconds_bucket{le=\"+Inf\"} [5m])) - sum(rate(aidbox_http_request_duration_seconds_bucket{le=\"0.5\"} [5m]))",
     "legendFormat": "> 0.5 sec"
    },
    { "expr": "rate(pg_requests_total[5m])", "legendFormat": "db req" }
   ]
  },
  {
   "title": "request dist",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(30, rate(aidbox_http_request_duration_seconds_sum[30m]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "req mean dist",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, rate(aidbox_http_request_duration_seconds_sum[30m])/rate(aidbox_http_request_duration_seconds_count[30m]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(aidbox_http_request_duration_seconds_count{status=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    },
    { "expr": "rate(hikari_timeout_total[5m])", "legendFormat": "db conn err" },
    {}
   ]
  },
  {
   "title": "resp statuses",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aidbox_http_request_duration_seconds_count[30m]))  by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_heap_memory", "legendFormat": "heap" },
    { "expr": "jvm_non_heap_memory", "legendFormat": "non-heap" }
   ]
  },
  {
   "title": "duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(aidbox_http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "sum(rate(aidbox_http_request_duration_seconds_sum[1m]))/sum(rate(aidbox_http_request_duration_seconds_count[1m]))",
     "legendFormat": "box avg"
    },
    {
     "expr": "rate(pg_requests_duration_seconds_sum[1m])/rate(pg_requests_total[1m])",
     "legendFormat": "db avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(aidbox_http_request_wait_seconds_bucket[1m])) by (le))",
     "legendFormat": "wait99"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(aidbox_http_request_wait_seconds_bucket[1m])) by (le))",
     "legendFormat": "wait75"
    },
    {
     "expr": "rate(hikari_acquire_wait_seconds_sum[1m])/rate(hikari_acquire_wait_seconds_count[1m])",
     "legendFormat": "hikari wait"
    }
   ]
  },
  {
   "title": "jvm threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    { "expr": "jvm_thread_count", "legendFormat": "threads" },
    { "expr": "jvm_thread_peak_count", "legendFormat": "threads peak" },
    { "expr": "jvm_thread_daemon_count", "legendFormat": "daemon" }
   ]
  },
  {
   "title": "pools",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "httpkit_active_count", "legendFormat": "http active" },
    { "expr": "hikari_active_count", "legendFormat": "hikari active" },
    { "expr": "pg_activity_count", "legendFormat": "db {{state}}" },
    { "expr": "hikari_idle_count", "legendFormat": "hikari idle" },
    { "expr": "httpkit_max_size", "legendFormat": "http max" },
    { "expr": "hikari_max_size", "legendFormat": "hikari max" }
   ]
  },
  {
   "title": "Slow Mean ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, rate(aidbox_http_request_duration_seconds_sum[5m])/rate(aidbox_http_request_duration_seconds_count[5m]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Slow Sum",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, rate(aidbox_http_request_duration_seconds_sum[1m]))",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}