{
 "title": "Postgres Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Idx vs Seq Scans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(pg_idx_scan[15m]))",
     "legendFormat": "idx scans"
    },
    {
     "expr": "sum(increase(pg_seq_scan[15m]))",
     "legendFormat": "seq scans"
    }
   ]
  },
  {
   "title": "Idx Scans",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum(increase(pg_idx_scan[15m])) by (table_name)))"
    }
   ]
  },
  {
   "title": "Seq Scans",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(topk(10, sum(increase(pg_seq_scan[15m])) by (table_name)))"
    }
   ]
  },
  {
   "title": "Rows Fetched & Returned",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 8 },
   "targets": [
    { "expr": "increase(pg_tup_returned[5m])", "legendFormat": "returned" },
    { "expr": "increase(pg_tup_fetched[5m])", "legendFormat": "fetched" }
   ]
  },
  {
   "title": "Cache Usage vs DIsk Reads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 8 },
   "targets": [
    { "expr": "increase(pg_blks_read[5m])", "legendFormat": "read" },
    { "expr": "increase(pg_blks_hit[5m])", "legendFormat": "cache" }
   ]
  }
 ]
}